{"name": "Test Login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114\nCurrent browser version is 119.0.6045.124 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00E7A813+48355]\n\t(No symbol) [0x00E0C4B1]\n\t(No symbol) [0x00D15358]\n\t(No symbol) [0x00D361AC]\n\t(No symbol) [0x00D31EF3]\n\t(No symbol) [0x00D30579]\n\t(No symbol) [0x00D60C55]\n\t(No symbol) [0x00D6093C]\n\t(No symbol) [0x00D5A536]\n\t(No symbol) [0x00D382DC]\n\t(No symbol) [0x00D393DD]\n\tGetHandleVerifier [0x010DAABD+2539405]\n\tGetHandleVerifier [0x0111A78F+2800735]\n\tGetHandleVerifier [0x0111456C+2775612]\n\tGetHandleVerifier [0x00F051E0+616112]\n\t(No symbol) [0x00E15F8C]\n\t(No symbol) [0x00E12328]\n\t(No symbol) [0x00E1240B]\n\t(No symbol) [0x00E04FF7]\n\tBaseThreadInitThunk [0x756C7BA9+25]\n\tRtlInitializeExceptionChain [0x7722BD2B+107]\n\tRtlClearBits [0x7722BCAF+191]\n\n", "trace": "  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\step_definitions_login.py\", line 12, in visit_site\n    context.driver = webdriver.Edge(options=options)\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\edge\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 289, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Visit Site", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114\nCurrent browser version is 119.0.6045.124 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00E7A813+48355]\n\t(No symbol) [0x00E0C4B1]\n\t(No symbol) [0x00D15358]\n\t(No symbol) [0x00D361AC]\n\t(No symbol) [0x00D31EF3]\n\t(No symbol) [0x00D30579]\n\t(No symbol) [0x00D60C55]\n\t(No symbol) [0x00D6093C]\n\t(No symbol) [0x00D5A536]\n\t(No symbol) [0x00D382DC]\n\t(No symbol) [0x00D393DD]\n\tGetHandleVerifier [0x010DAABD+2539405]\n\tGetHandleVerifier [0x0111A78F+2800735]\n\tGetHandleVerifier [0x0111456C+2775612]\n\tGetHandleVerifier [0x00F051E0+616112]\n\t(No symbol) [0x00E15F8C]\n\t(No symbol) [0x00E12328]\n\t(No symbol) [0x00E1240B]\n\t(No symbol) [0x00E04FF7]\n\tBaseThreadInitThunk [0x756C7BA9+25]\n\tRtlInitializeExceptionChain [0x7722BD2B+107]\n\tRtlClearBits [0x7722BCAF+191]\n\n", "trace": "  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\step_definitions_login.py\", line 12, in visit_site\n    context.driver = webdriver.Edge(options=options)\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\edge\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 289, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Rakesh\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1699678098069, "stop": 1699678103324}, {"name": "When I Enter Username and Password", "status": "skipped", "start": 1699678103325, "stop": 1699678103325}], "start": 1699678098066, "stop": 1699678103325, "uuid": "6db8ecdd-5361-41a8-ad31-7d141be082d7", "historyId": "6e2fd007c9e5948d53fd27d11287c638", "fullName": "Login Successfully: Test Login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login Successfully"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}